DROP TABLE IF EXISTS trees;
CREATE TABLE trees (id INT NOT NULL, species VARCHAR(255), name VARCHAR(255) NOT NULL);
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, username VARCHAR(255), password VARCHAR(255) NOT NULL);
